/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProgressRouteImport } from './routes/dashboard/progress'
import { Route as DashboardPracticeRouteImport } from './routes/dashboard/practice'
import { Route as DashboardChallengesRouteImport } from './routes/dashboard/challenges'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardPracticeIndexRouteImport } from './routes/dashboard/practice/index'
import { Route as DashboardPracticeWordchunkingPracticeIdRouteImport } from './routes/dashboard/practice/wordchunking/$practiceId'
import { Route as DashboardPracticeTeleprompterPracticeIdRouteImport } from './routes/dashboard/practice/teleprompter/$practiceId'
import { Route as DashboardPracticeSpeedreadingPracticeIdRouteImport } from './routes/dashboard/practice/speedreading/$practiceId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChallengesRoute = DashboardChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardPracticeIndexRoute = DashboardPracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPracticeRoute,
} as any)
const DashboardPracticeWordchunkingPracticeIdRoute =
  DashboardPracticeWordchunkingPracticeIdRouteImport.update({
    id: '/wordchunking/$practiceId',
    path: '/wordchunking/$practiceId',
    getParentRoute: () => DashboardPracticeRoute,
  } as any)
const DashboardPracticeTeleprompterPracticeIdRoute =
  DashboardPracticeTeleprompterPracticeIdRouteImport.update({
    id: '/teleprompter/$practiceId',
    path: '/teleprompter/$practiceId',
    getParentRoute: () => DashboardPracticeRoute,
  } as any)
const DashboardPracticeSpeedreadingPracticeIdRoute =
  DashboardPracticeSpeedreadingPracticeIdRouteImport.update({
    id: '/speedreading/$practiceId',
    path: '/speedreading/$practiceId',
    getParentRoute: () => DashboardPracticeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/practice': typeof DashboardPracticeRouteWithChildren
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/practice/': typeof DashboardPracticeIndexRoute
  '/dashboard/practice/speedreading/$practiceId': typeof DashboardPracticeSpeedreadingPracticeIdRoute
  '/dashboard/practice/teleprompter/$practiceId': typeof DashboardPracticeTeleprompterPracticeIdRoute
  '/dashboard/practice/wordchunking/$practiceId': typeof DashboardPracticeWordchunkingPracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/practice': typeof DashboardPracticeIndexRoute
  '/dashboard/practice/speedreading/$practiceId': typeof DashboardPracticeSpeedreadingPracticeIdRoute
  '/dashboard/practice/teleprompter/$practiceId': typeof DashboardPracticeTeleprompterPracticeIdRoute
  '/dashboard/practice/wordchunking/$practiceId': typeof DashboardPracticeWordchunkingPracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/practice': typeof DashboardPracticeRouteWithChildren
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/practice/': typeof DashboardPracticeIndexRoute
  '/dashboard/practice/speedreading/$practiceId': typeof DashboardPracticeSpeedreadingPracticeIdRoute
  '/dashboard/practice/teleprompter/$practiceId': typeof DashboardPracticeTeleprompterPracticeIdRoute
  '/dashboard/practice/wordchunking/$practiceId': typeof DashboardPracticeWordchunkingPracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/challenges'
    | '/dashboard/practice'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/practice/'
    | '/dashboard/practice/speedreading/$practiceId'
    | '/dashboard/practice/teleprompter/$practiceId'
    | '/dashboard/practice/wordchunking/$practiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/challenges'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/practice'
    | '/dashboard/practice/speedreading/$practiceId'
    | '/dashboard/practice/teleprompter/$practiceId'
    | '/dashboard/practice/wordchunking/$practiceId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/challenges'
    | '/dashboard/practice'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/practice/'
    | '/dashboard/practice/speedreading/$practiceId'
    | '/dashboard/practice/teleprompter/$practiceId'
    | '/dashboard/practice/wordchunking/$practiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice': {
      id: '/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/challenges': {
      id: '/dashboard/challenges'
      path: '/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof DashboardChallengesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/practice/': {
      id: '/dashboard/practice/'
      path: '/'
      fullPath: '/dashboard/practice/'
      preLoaderRoute: typeof DashboardPracticeIndexRouteImport
      parentRoute: typeof DashboardPracticeRoute
    }
    '/dashboard/practice/wordchunking/$practiceId': {
      id: '/dashboard/practice/wordchunking/$practiceId'
      path: '/wordchunking/$practiceId'
      fullPath: '/dashboard/practice/wordchunking/$practiceId'
      preLoaderRoute: typeof DashboardPracticeWordchunkingPracticeIdRouteImport
      parentRoute: typeof DashboardPracticeRoute
    }
    '/dashboard/practice/teleprompter/$practiceId': {
      id: '/dashboard/practice/teleprompter/$practiceId'
      path: '/teleprompter/$practiceId'
      fullPath: '/dashboard/practice/teleprompter/$practiceId'
      preLoaderRoute: typeof DashboardPracticeTeleprompterPracticeIdRouteImport
      parentRoute: typeof DashboardPracticeRoute
    }
    '/dashboard/practice/speedreading/$practiceId': {
      id: '/dashboard/practice/speedreading/$practiceId'
      path: '/speedreading/$practiceId'
      fullPath: '/dashboard/practice/speedreading/$practiceId'
      preLoaderRoute: typeof DashboardPracticeSpeedreadingPracticeIdRouteImport
      parentRoute: typeof DashboardPracticeRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardPracticeRouteChildren {
  DashboardPracticeIndexRoute: typeof DashboardPracticeIndexRoute
  DashboardPracticeSpeedreadingPracticeIdRoute: typeof DashboardPracticeSpeedreadingPracticeIdRoute
  DashboardPracticeTeleprompterPracticeIdRoute: typeof DashboardPracticeTeleprompterPracticeIdRoute
  DashboardPracticeWordchunkingPracticeIdRoute: typeof DashboardPracticeWordchunkingPracticeIdRoute
}

const DashboardPracticeRouteChildren: DashboardPracticeRouteChildren = {
  DashboardPracticeIndexRoute: DashboardPracticeIndexRoute,
  DashboardPracticeSpeedreadingPracticeIdRoute:
    DashboardPracticeSpeedreadingPracticeIdRoute,
  DashboardPracticeTeleprompterPracticeIdRoute:
    DashboardPracticeTeleprompterPracticeIdRoute,
  DashboardPracticeWordchunkingPracticeIdRoute:
    DashboardPracticeWordchunkingPracticeIdRoute,
}

const DashboardPracticeRouteWithChildren =
  DashboardPracticeRoute._addFileChildren(DashboardPracticeRouteChildren)

interface DashboardRouteChildren {
  DashboardChallengesRoute: typeof DashboardChallengesRoute
  DashboardPracticeRoute: typeof DashboardPracticeRouteWithChildren
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChallengesRoute: DashboardChallengesRoute,
  DashboardPracticeRoute: DashboardPracticeRouteWithChildren,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
