/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOnboardingLayoutRouteImport } from './routes/onboarding/_onboardingLayout'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as OnboardingOnboardingLayoutIndexRouteImport } from './routes/onboarding/_onboardingLayout/index'
import { Route as DashboardDashboardLayoutIndexRouteImport } from './routes/dashboard/_dashboardLayout/index'
import { Route as DashboardDashboardLayoutProgressRouteImport } from './routes/dashboard/_dashboardLayout/progress'
import { Route as DashboardDashboardLayoutChallengesRouteImport } from './routes/dashboard/_dashboardLayout/challenges'
import { Route as DashboardDashboardLayoutPracticePracticeLayoutRouteImport } from './routes/dashboard/_dashboardLayout/practice/_practice-layout'
import { Route as DashboardDashboardLayoutPracticePracticeLayoutIndexRouteImport } from './routes/dashboard/_dashboardLayout/practice/_practice-layout/index'
import { Route as DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRouteImport } from './routes/dashboard/_dashboardLayout/practice/_practice-layout/speedreading/$practiceId'

const OnboardingRouteImport = createFileRoute('/onboarding')()
const DashboardRouteImport = createFileRoute('/dashboard')()
const DashboardDashboardLayoutPracticeRouteImport = createFileRoute(
  '/dashboard/_dashboardLayout/practice',
)()

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingLayoutRoute =
  OnboardingOnboardingLayoutRouteImport.update({
    id: '/_onboardingLayout',
    getParentRoute: () => OnboardingRoute,
  } as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardLayoutPracticeRoute =
  DashboardDashboardLayoutPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const OnboardingOnboardingLayoutIndexRoute =
  OnboardingOnboardingLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OnboardingOnboardingLayoutRoute,
  } as any)
const DashboardDashboardLayoutIndexRoute =
  DashboardDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutProgressRoute =
  DashboardDashboardLayoutProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutChallengesRoute =
  DashboardDashboardLayoutChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutPracticePracticeLayoutRoute =
  DashboardDashboardLayoutPracticePracticeLayoutRouteImport.update({
    id: '/_practice-layout',
    getParentRoute: () => DashboardDashboardLayoutPracticeRoute,
  } as any)
const DashboardDashboardLayoutPracticePracticeLayoutIndexRoute =
  DashboardDashboardLayoutPracticePracticeLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutPracticePracticeLayoutRoute,
  } as any)
const DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute =
  DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRouteImport.update(
    {
      id: '/speedreading/$practiceId',
      path: '/speedreading/$practiceId',
      getParentRoute: () => DashboardDashboardLayoutPracticePracticeLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardDashboardLayoutRouteWithChildren
  '/onboarding': typeof OnboardingOnboardingLayoutRouteWithChildren
  '/dashboard/challenges': typeof DashboardDashboardLayoutChallengesRoute
  '/dashboard/progress': typeof DashboardDashboardLayoutProgressRoute
  '/dashboard/': typeof DashboardDashboardLayoutIndexRoute
  '/onboarding/': typeof OnboardingOnboardingLayoutIndexRoute
  '/dashboard/practice': typeof DashboardDashboardLayoutPracticePracticeLayoutRouteWithChildren
  '/dashboard/practice/': typeof DashboardDashboardLayoutPracticePracticeLayoutIndexRoute
  '/dashboard/practice/speedreading/$practiceId': typeof DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardDashboardLayoutIndexRoute
  '/onboarding': typeof OnboardingOnboardingLayoutIndexRoute
  '/dashboard/challenges': typeof DashboardDashboardLayoutChallengesRoute
  '/dashboard/progress': typeof DashboardDashboardLayoutProgressRoute
  '/dashboard/practice': typeof DashboardDashboardLayoutPracticePracticeLayoutIndexRoute
  '/dashboard/practice/speedreading/$practiceId': typeof DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/_onboardingLayout': typeof OnboardingOnboardingLayoutRouteWithChildren
  '/dashboard/_dashboardLayout/challenges': typeof DashboardDashboardLayoutChallengesRoute
  '/dashboard/_dashboardLayout/progress': typeof DashboardDashboardLayoutProgressRoute
  '/dashboard/_dashboardLayout/': typeof DashboardDashboardLayoutIndexRoute
  '/onboarding/_onboardingLayout/': typeof OnboardingOnboardingLayoutIndexRoute
  '/dashboard/_dashboardLayout/practice': typeof DashboardDashboardLayoutPracticeRouteWithChildren
  '/dashboard/_dashboardLayout/practice/_practice-layout': typeof DashboardDashboardLayoutPracticePracticeLayoutRouteWithChildren
  '/dashboard/_dashboardLayout/practice/_practice-layout/': typeof DashboardDashboardLayoutPracticePracticeLayoutIndexRoute
  '/dashboard/_dashboardLayout/practice/_practice-layout/speedreading/$practiceId': typeof DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/challenges'
    | '/dashboard/progress'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/practice'
    | '/dashboard/practice/'
    | '/dashboard/practice/speedreading/$practiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/challenges'
    | '/dashboard/progress'
    | '/dashboard/practice'
    | '/dashboard/practice/speedreading/$practiceId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/_dashboardLayout'
    | '/onboarding'
    | '/onboarding/_onboardingLayout'
    | '/dashboard/_dashboardLayout/challenges'
    | '/dashboard/_dashboardLayout/progress'
    | '/dashboard/_dashboardLayout/'
    | '/onboarding/_onboardingLayout/'
    | '/dashboard/_dashboardLayout/practice'
    | '/dashboard/_dashboardLayout/practice/_practice-layout'
    | '/dashboard/_dashboardLayout/practice/_practice-layout/'
    | '/dashboard/_dashboardLayout/practice/_practice-layout/speedreading/$practiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_onboardingLayout': {
      id: '/onboarding/_onboardingLayout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingLayoutRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_dashboardLayout/practice': {
      id: '/dashboard/_dashboardLayout/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardDashboardLayoutPracticeRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/onboarding/_onboardingLayout/': {
      id: '/onboarding/_onboardingLayout/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingOnboardingLayoutIndexRouteImport
      parentRoute: typeof OnboardingOnboardingLayoutRoute
    }
    '/dashboard/_dashboardLayout/': {
      id: '/dashboard/_dashboardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/progress': {
      id: '/dashboard/_dashboardLayout/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardDashboardLayoutProgressRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/challenges': {
      id: '/dashboard/_dashboardLayout/challenges'
      path: '/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof DashboardDashboardLayoutChallengesRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/practice/_practice-layout': {
      id: '/dashboard/_dashboardLayout/practice/_practice-layout'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutRouteImport
      parentRoute: typeof DashboardDashboardLayoutPracticeRoute
    }
    '/dashboard/_dashboardLayout/practice/_practice-layout/': {
      id: '/dashboard/_dashboardLayout/practice/_practice-layout/'
      path: '/'
      fullPath: '/dashboard/practice/'
      preLoaderRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutRoute
    }
    '/dashboard/_dashboardLayout/practice/_practice-layout/speedreading/$practiceId': {
      id: '/dashboard/_dashboardLayout/practice/_practice-layout/speedreading/$practiceId'
      path: '/speedreading/$practiceId'
      fullPath: '/dashboard/practice/speedreading/$practiceId'
      preLoaderRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRouteImport
      parentRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutRoute
    }
  }
}

interface DashboardDashboardLayoutPracticePracticeLayoutRouteChildren {
  DashboardDashboardLayoutPracticePracticeLayoutIndexRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutIndexRoute
  DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute
}

const DashboardDashboardLayoutPracticePracticeLayoutRouteChildren: DashboardDashboardLayoutPracticePracticeLayoutRouteChildren =
  {
    DashboardDashboardLayoutPracticePracticeLayoutIndexRoute:
      DashboardDashboardLayoutPracticePracticeLayoutIndexRoute,
    DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute:
      DashboardDashboardLayoutPracticePracticeLayoutSpeedreadingPracticeIdRoute,
  }

const DashboardDashboardLayoutPracticePracticeLayoutRouteWithChildren =
  DashboardDashboardLayoutPracticePracticeLayoutRoute._addFileChildren(
    DashboardDashboardLayoutPracticePracticeLayoutRouteChildren,
  )

interface DashboardDashboardLayoutPracticeRouteChildren {
  DashboardDashboardLayoutPracticePracticeLayoutRoute: typeof DashboardDashboardLayoutPracticePracticeLayoutRouteWithChildren
}

const DashboardDashboardLayoutPracticeRouteChildren: DashboardDashboardLayoutPracticeRouteChildren =
  {
    DashboardDashboardLayoutPracticePracticeLayoutRoute:
      DashboardDashboardLayoutPracticePracticeLayoutRouteWithChildren,
  }

const DashboardDashboardLayoutPracticeRouteWithChildren =
  DashboardDashboardLayoutPracticeRoute._addFileChildren(
    DashboardDashboardLayoutPracticeRouteChildren,
  )

interface DashboardDashboardLayoutRouteChildren {
  DashboardDashboardLayoutChallengesRoute: typeof DashboardDashboardLayoutChallengesRoute
  DashboardDashboardLayoutProgressRoute: typeof DashboardDashboardLayoutProgressRoute
  DashboardDashboardLayoutIndexRoute: typeof DashboardDashboardLayoutIndexRoute
  DashboardDashboardLayoutPracticeRoute: typeof DashboardDashboardLayoutPracticeRouteWithChildren
}

const DashboardDashboardLayoutRouteChildren: DashboardDashboardLayoutRouteChildren =
  {
    DashboardDashboardLayoutChallengesRoute:
      DashboardDashboardLayoutChallengesRoute,
    DashboardDashboardLayoutProgressRoute:
      DashboardDashboardLayoutProgressRoute,
    DashboardDashboardLayoutIndexRoute: DashboardDashboardLayoutIndexRoute,
    DashboardDashboardLayoutPracticeRoute:
      DashboardDashboardLayoutPracticeRouteWithChildren,
  }

const DashboardDashboardLayoutRouteWithChildren =
  DashboardDashboardLayoutRoute._addFileChildren(
    DashboardDashboardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingOnboardingLayoutRouteChildren {
  OnboardingOnboardingLayoutIndexRoute: typeof OnboardingOnboardingLayoutIndexRoute
}

const OnboardingOnboardingLayoutRouteChildren: OnboardingOnboardingLayoutRouteChildren =
  {
    OnboardingOnboardingLayoutIndexRoute: OnboardingOnboardingLayoutIndexRoute,
  }

const OnboardingOnboardingLayoutRouteWithChildren =
  OnboardingOnboardingLayoutRoute._addFileChildren(
    OnboardingOnboardingLayoutRouteChildren,
  )

interface OnboardingRouteChildren {
  OnboardingOnboardingLayoutRoute: typeof OnboardingOnboardingLayoutRouteWithChildren
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingLayoutRoute: OnboardingOnboardingLayoutRouteWithChildren,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
